### ISSUE TITLE
If version is not specified installation fails

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/setup-dvc#9]
Version should be ```latest``` by default. However this works

```yaml
- uses: iterative/setup-dvc@v1
        with:
          version: 'latest'
```

and this returns an error

```yaml
- uses: iterative/setup-dvc@v1
```

![image](https://user-images.githubusercontent.com/414967/106515277-b99fc780-64d5-11eb-9738-3462e04dea7f.png)

```
Run iterative/setup-dvc@v1
Error: Command failed: /usr/bin/sudo dpkg -i 'dvc.deb' && /usr/bin/sudo rm -f 'dvc.deb'
dpkg-deb: error: 'dvc.deb' is not a Debian format archive
dpkg: error processing archive dvc.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 dvc.deb
```

**Comment by fabiosantoscode** [comment]
I get this sometimes when installing deb packages by file path. Usually `apt-get install ./package.deb` fixes it (the ./ makes it not look up the package in its internal list) but I have no idea why.

**Comment by DavidGOrtega** [comment]
@fabiosantoscode I got this error 1 out of 20 times, I was hoping to be differences in the GH image. But its also very hard to fix it because it's very hard to repro it.

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega: hopefully, we'll notice the next time it happens: 
https://github.com/0x2b3bfa0/dvc-action-test/actions

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, I can beat your record: 0 of 25 times! 😄  I'll leave it running for a week, but it might have been resolved already. 🤔

**Comment by 0x2b3bfa0** [comment]
## Error

```console
# apt install ··· ./dvc.deb
E: Invalid archive signature
E: Internal error, could not locate member control.tar.{zstlz4gzxzbz2lzma}
E: Could not read meta data from /home/runner/work/dvc-action-test/dvc-action-test/dvc.deb
E: The package lists or status file could not be parsed or opened.
```

## Timeline

* [`2021-03-03 10:21:40`](https://github.com/iterative/dvc/releases/tag/2.0.0) — Source release published.
* [`2021-03-03 10:26:40`](https://github.com/0x2b3bfa0/dvc-action-test/runs/2021150987) — Bug successfully reproduced.
* [`2021-03-03 10:27:13`](https://github.com/iterative/dvc/runs/2021155156) — Debian package asset uploaded.

## Cause

This race condition will happen in a time window of approximately 10 minutes after each DVC release, because published releases appear as `latest` even before triggering the platform-specific asset building actions, and the code on this repository does not consider this particular edge case.

https://github.com/iterative/setup-dvc/blob/19880d0a5db4e67b5847b5fcfb9cbc7c7e13c07f/src/utils.js#L34-L40

This issue was specially hard to narrow down because the `404` error for the package artifact wasn't being handled on the code, causing `apt` to be fed with the contents of an error page instead of the expected package file; checking for a successful response through the [`res.ok`](https://fetch.spec.whatwg.org/#dom-response-ok) property would probably have produced a more meaningful error.

https://github.com/iterative/setup-dvc/blob/19880d0a5db4e67b5847b5fcfb9cbc7c7e13c07f/src/utils.js#L20-L32

After reviewing the code, I'm inclined to think that there would not be any difference between specifying `version: 'latest'` and not specifying any version, so the observation in the original post would only be a direct consequence of the erratic nature of this issue.

https://github.com/iterative/setup-dvc/blob/19880d0a5db4e67b5847b5fcfb9cbc7c7e13c07f/src/utils.js#L44

## Solution

We could check the latest version for matching assets and, if there isn't any, resort to the penultimate version.

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, which of these solutions would you prefer? Would using `pip` on macOS and Debian distributions cause any issue?

**Comment by DavidGOrtega** [comment]
Awesome catch!

> Not feasible due to the GitHub API rate limits for unauthenticated users; asking for a GITHUB_TOKEN is impractical.

GITHUB_TOKEN is accesible in the workflow. Is that GITHUB_TOKEN that you are referring to?

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, yes, it's accessible, but it doesn't look appropriate to ask for it when setting up a workflow dependency; at least, not without an excellent reason. 

I would prefer either (1) to get DVC to publish releases once assets have been uploaded, or (2) to install the package from other official sources as @efiop suggested [here](https://github.com/iterative/dvc/issues/5542). Nevertheless, it looks like our `brew` recipe only has the latest version and we would have to run the extra mile anyways.

**Comment by DavidGOrtega** [comment]
>  but it doesn't look appropriate to ask for it when setting up a workflow dependency; at least, not without an excellent reason.

You mean this?
```yaml
     - uses: iterative/setup-cml@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
```

**Comment by 0x2b3bfa0** [comment]
Exactly

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, I would propose #12 to fix this issue: it uses `pip` packages for all the runner operating systems.

**Comment by 0x2b3bfa0** [comment]
Definitely, the ideal solution would be having all the DVC release assets uploaded before publishing. All the alternatives I can think of would add up to the technical debt laundry list, one way or another.

<details><summary><i>📖 &nbsp;&nbsp;Note: this issue reduces our layman availability metric to 99.88 %</i></summary>
<br>

Considering that the [`build packages`](https://github.com/iterative/dvc/actions/runs/622724075) action takes approximately 8 minutes to upload the release assets after publishing, we can perform some quick downtime estimations with the following formulas:

```python
release_dates = [
    1614942525,
    1614900985,
    1614785918,
    1614766914,
    1614715882,
    1614615657,
    1614106844,
    1614339349,
    1613533904,
    1613415465,
    1612260018,
    1612208847,
    1611628591,
    1611527735,
    1611227359,
    1609850097,
    1608723473,
    1608124083,
    1608054971,
    1607970359,
    1607819710,
    1607443941,
    1606930143,
    1606926602,
    1606924068,
    1606235653,
    1605813745,
    1605662310,
    1603812829,
    1603387362
]

release_intervals = [
    abs(first - second)
    for first, second in
    zip(releases, releases[1:])
]

average_release_interval = sum(release_intervals) / len(release_intervals)
estimated_downtime_ratio = 8 * 60 / average_release_interval

print(f"Estimated availability {1 - estimated_downtime_ratio:.2%}")
```

</details>
